name: release

on:
  workflow_dispatch:
    inputs:
      version_scale:
        type: choice
        description: Release Scale
        options:
        - patch
        - minor
        - major

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with: 
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Configure Git User
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"

      - name: Use Node.js 14.x
        uses: actions/setup-node@v3
        with:
          node-version: "14.x"
          registry-url: https://registry.npmjs.org

      - name: NPM Install
        run: npm install

      - name: Thundra Registry
        run: |
          npm config set registry ${{ secrets.THUNDRA_REGISTRY }}
          npm config set _auth ${{ secrets.THUNDRA_REGISTRY_AUTH }}

      - name: NPM Build
        run: npm run clean-build:all

      - name: NPM Publish
        run: npm run release
        env:
          RELEASE_SCALE: ${{ github.event.inputs.version_scale }}
          # NODE_AUTH_TOKEN: ${{ secrets.FORESIGHT_NPM_PUBLISH_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}