name: sync-api-pr

on:
  workflow_dispatch:
    inputs:
      api_spec_url:
        description: "Api Spec Url"
        required: true
        default: "https://api.service.runforesight.us/v2/api-docs"
  
jobs:
  tryer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node 14.x 
        uses: actions/setup-node@v3
        with:
          node-version: 14.x
      - name: Configure Git User
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
      - name: Install openapi-generator-cli
        run:  npm install @openapitools/openapi-generator-cli -g
      - name: Create Branch
        run:  git checkout -b 'feature/sync-repo'
      - name: Install Dependencies
        run:  npm i
      - name: Get Api Spec
        run:  wget ${{ github.event.inputs.api_spec_url }} -O api-spec.json
      - name: Generate Client
        run:  openapi-generator-cli generate -i ./api-spec.json -g typescript-axios -o ./src
      - name: Remove Redundant Files
        run:  rm -R  src/.openapi-generator && rm -R src/.openapi-generator-ignore
      - name: git status
        run:  git status
      - name: git add
        run:  git add src/**
      - name: git commit
        run:  git commit -m "Repo Sync"
      - name: git pusg
        run:  git push origin feature/sync-repo
      - name: create pull request
        run:  gh pr create -B master -H 'feature/sync-repo' --title 'Repo Sync' --body 'Created by Github action'
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}